### ISSUE TITLE
请教在studio中使用robotium

### ISSUE THREAD

**Issue by objectBoolean** [huangDawn/robotium-android-studio-handbook#4]
你好！你的robotium-android-studio-handbook中的方法现在不起作用了。有其他方法更新吗？

**Comment by huangDawn** [comment]
具体哪些不起作用了呢？我这边还可以用

2017年1月18日 11:31，"objectBoolean" <notifications@github.com>写道：

**Comment by objectBoolean** [comment]
@huangDawn 
Error:(59, 0) Could not get unknown property 'assembleDebug' for project ':app' of type org.gradle.api.Project.
<a href="openFile:E:\Android_workspace\MyApplication2\app\build.gradle">Open File</a>

就是assembleDebug.dependsOn copyTask 这句不对

**Comment by objectBoolean** [comment]
能加个QQ吗，请指教306695293

**Comment by objectBoolean** [comment]
哈哈，我搞定了
